# Generated by Django 4.1.4 on 2023-05-29 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('role', models.CharField(default='管理员', max_length=32, verbose_name='角色')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('studentId', models.CharField(max_length=32, verbose_name='学号')),
                ('college', models.CharField(max_length=32, verbose_name='学院')),
                ('major', models.CharField(max_length=32, verbose_name='专业')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('sex', models.IntegerField(choices=[(0, '女'), (1, '男')], verbose_name='性别')),
                ('role', models.CharField(default='学生', max_length=32, verbose_name='角色')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('teacherId', models.CharField(max_length=32, verbose_name='教职工号')),
                ('college', models.CharField(max_length=32, verbose_name='学院')),
                ('itro', models.CharField(blank=True, max_length=32, verbose_name='教师介绍')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('phone', models.CharField(max_length=64, verbose_name='教师电话')),
                ('sex', models.IntegerField(choices=[(0, '女'), (1, '男')], verbose_name='性别')),
                ('role', models.CharField(default='教师', max_length=32, verbose_name='角色')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='论文标题')),
                ('topicDirect', models.CharField(max_length=32, verbose_name='论文方向')),
                ('maxNum', models.IntegerField(verbose_name='限定人数')),
                ('teacherName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teachers', verbose_name='教师姓名')),
            ],
        ),
    ]
