# Generated by Django 4.1.4 on 2023-05-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='studentId',
            field=models.IntegerField(verbose_name='学号'),
        ),
    ]
