# Generated by Django 4.1.4 on 2023-05-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_students_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='studentId',
            field=models.BigIntegerField(verbose_name='学号'),
        ),
    ]
