# Generated by Django 4.1.4 on 2023-05-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_students_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='teacherId',
            field=models.BigIntegerField(max_length=32, verbose_name='教职工号'),
        ),
    ]
