# Generated by Django 4.1.4 on 2023-08-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_teachers_teacherid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='teacherId',
            field=models.BigIntegerField(verbose_name='教职工号'),
        ),
        migrations.CreateModel(
            name='TopicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.students', verbose_name='学生id')),
                ('topicTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.topic', verbose_name='论文id')),
            ],
        ),
    ]
